name: laravel_app
services:
  php:
    image: php:8.4-fpm
    build: ./php
    volumes:
      - ./src:/var/www/html
      - ./php/conf.d/99-xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=alumno
      - MYSQL_PASSWORD=alumno
      - MYSQL_DB=test
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: administrador
      MYSQL_USER: alumno
      MYSQL_PASSWORD: alumno
      MYSQL_DATABASE: test
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/tmp:/tmp
    ports:
      - "3306:3306"
    networks:
      - default

networks:
 default:
   driver: bridge